import { PromptTemplate } from '@/types/chat';

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'p-mortgage-1',
    title: '15 vs 30-Year Mortgage Analysis',
    description: 'Calculate monthly payments, lifetime interest cost, and savings comparison.',
    category: 'Finance',
    icon: 'home-outline',
    modelId: 'mortx-finance',
    prompt: 'Compare a 15-year vs 30-year fixed rate mortgage for a $450,000 loan at 6.75% interest. Show monthly payment difference and lifetime interest savings.',
  },
  {
    id: 'p-mortgage-2',
    title: 'Bi-Weekly Payment Payoff Calculator',
    description: 'Understand how paying every two weeks accelerates loan payoff.',
    category: 'Finance',
    icon: 'calculator-outline',
    modelId: 'mortx-finance',
    prompt: 'Explain how bi-weekly mortgage payments work, how much interest it cuts off a $350k mortgage, and whether lenders accept this.',
  },
  {
    id: 'p-code-1',
    title: 'Async Debounce Function in TypeScript',
    description: 'Write a type-safe asynchronous debounce helper with cleanup.',
    category: 'Coding',
    icon: 'code-slash-outline',
    modelId: 'mortx-coder',
    prompt: 'Write a production-grade TypeScript debounceAsync function with generic type arguments, cancellation token, and proper cleanup.',
  },
  {
    id: 'p-code-2',
    title: 'React Native FlatList Performance Audit',
    description: 'Optimize long lists, item layouts, and memoization in mobile apps.',
    category: 'Coding',
    icon: 'phone-portrait-outline',
    modelId: 'mortx-coder',
    prompt: 'Give me a senior-level checklist and code examples to optimize FlatList performance in React Native with 10,000+ items.',
  },
  {
    id: 'p-writing-1',
    title: 'Executive Salary Review Request',
    description: 'Draft an assertive, diplomatic, and persuasive email to your manager.',
    category: 'Writing',
    icon: 'mail-outline',
    modelId: 'mortx-4o',
    prompt: 'Draft a polite and confident email to my VP requesting a performance-based compensation review, highlighting recent high-impact project wins.',
  },
  {
    id: 'p-writing-2',
    title: 'Product Launch Announcement Post',
    description: 'Write an engaging LinkedIn/Twitter announcement for a new tech product.',
    category: 'Writing',
    icon: 'megaphone-outline',
    modelId: 'mortx-4o',
    prompt: 'Write an exciting product launch announcement for MortX AI, emphasizing speed, deep reasoning, and specialized mortgage insights.',
  },
  {
    id: 'p-learning-1',
    title: 'How Transformer Models Work',
    description: 'Deconstruct self-attention mechanisms and neural language models.',
    category: 'Learning',
    icon: 'school-outline',
    modelId: 'mortx-r1',
    prompt: 'Explain the Transformer self-attention architecture step-by-step with clear analogies, query-key-value vectors, and why it revolutionized AI.',
  },
  {
    id: 'p-prod-1',
    title: 'Weekly Sprint Prioritization Framework',
    description: 'Structure tasks using Eisenhower matrix and high-leverage activities.',
    category: 'Productivity',
    icon: 'checkbox-outline',
    modelId: 'mortx-4o',
    prompt: 'Help me prioritize my upcoming weekly sprint using the Eisenhower matrix and 80/20 rule to maximize impact.',
  },
];
